### ISSUE TITLE
Add a dind volume driver.

### ISSUE THREAD

**Issue by jlevesy** [jlevesy/go-sind#30]
sind might needs a volume driver.

What we could do:

- Implement  a volume driver which creates and manage directory on an host volume using [this](https://github.com/docker/go-plugins-helpers/tree/master/volume) 
- On cluster create, spin up a "sidekick container" which exposes the driver process, expose its sockets and managed directory.

WDYT @dduportal ?

**Comment by dduportal** [comment]
I got mixed feelings about this:

- There is already the default volume driver (bind-mount), so data volumes works out of the box
- Installing another driver volume means additional plumbing, which can be really specific. I see this as an "application" deployment to be done after sind install.

Maybe it could be a mission for the manifests, as explained in #10 : manifests would describe the "plumbing" required AFTER the swarm cluster is ready, but BEFORE being able to deploy applications in this cluster. As manifests would solve the DockerEE problem (deploying the UCP service after swarm is ready), it would help here to express the following (sequential!) workflow:
- Deploy the required services (like a service for [minio](https://docs.minio.io/docs/deploy-minio-on-docker-swarm), or a NFS service, or whatever).

=> However, My mixed feelings come from the way how some storage drivers are working: it might require to operate at the docker engine, thus requiring to be operated before joining the swarm, and would imply some strong pattern changes on the node images (which are basically a simple `dockerd` process). Not even mentioning some NFSv2 (not NFSv4) which requires some specials kernel capabilities.

The second point you are mentioning is really interesting, as could also be see the "external" infra, to simulate technical services outside the swarm. Could be a good one to do, because it would avoid the nested dockerd features as well.

**Comment by jlevesy** [comment]
> There is already the default volume driver (bind-mount), so data volumes works out of the box

Nope, unfortunately this driver does not manage  "global" volumes.
